Rscine\AppBundle\Entity\Offer:
    constraints: ~
    properties:
        name:
            - NotBlank:
                message: offer.name.not_blank
                groups: [Default]
        description:
            - NotBlank:
                message: offer.description.not_blank
                groups: [Default]
