
users:
    type: rest
    resource: AppBundle\Controller\Api\UserController

counties:
    type: rest
    resource: AppBundle\Controller\Api\CountyController

departments:
    type: rest
    resource: AppBundle\Controller\Api\DepartmentController

individuals:
    type: rest
    resource: AppBundle\Controller\Api\IndividualController

companies:
    type: rest
    resource: AppBundle\Controller\Api\CompanyController

offers:
    type: rest
    resource: AppBundle\Controller\Api\OfferController
