
users:
    type: rest
    resource: AppBundle\Controller\Api\UserController

counties:
    type: rest
    resource: AppBundle\Controller\Api\CountyController

departments:
    type: rest
    resource: AppBundle\Controller\Api\DepartmentController

customers:
    type: rest
    resource: AppBundle\Controller\Api\CustomerController

contractor:
    type: rest
    resource: AppBundle\Controller\Api\ContractorController
