
users:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\UserController

counties:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\CountyController

disctricts:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\DistrictController

individuals:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\IndividualController

companies:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\CompanyController

offers:
    type: rest
    resource: Rscine\AppBundle\Controller\Api\OfferController
