
users:
    type: rest
    resource: AppBundle\Controller\Api\UserController

counties:
    type: rest
    resource: AppBundle\Controller\Api\CountyController

departments:
    type: rest
    resource: AppBundle\Controller\Api\DepartmentController
