
users:
    type: rest
    resource: UserBundle\Controller\Api\UserController

regions:
    type: rest
    resource: SocialBundle\Controller\Api\RegionController

disctricts:
    type: rest
    resource: SocialBundle\Controller\Api\DistrictController

persons:
    type: rest
    resource: SocialBundle\Controller\Api\PersonController

contactinformations:
    type: rest
    resource: SocialBundle\Controller\Api\ContactInformationController

companies:
    type: rest
    resource: SocialBundle\Controller\Api\CompanyController

offers:
    type: rest
    resource: OfferBundle\Controller\Api\OfferController

applicants:
    type:     rest
    parent:   offers
    resource: SocialBundle\Controller\Api\ApplicantController
