rscine_core:
    resource: "@RscineCoreBundle/Resources/config/routing.yml"
    prefix:   /

rscine_offer:
    resource: "@RscineOfferBundle/Resources/config/routing.yml"
    prefix:   /

rscine_user:
    resource: "@RscineUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /connect

# hwi_oauth_login:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login

api:
    type: rest
    resource: "api.yml"
    prefix: api/v1

api_login_check:
    path: /api/login_check
