rscine_o_auth_server:
    resource: "@RscineOAuthServerBundle/Resources/config/routing.yml"
    prefix:   /

rscine_worker:
    resource: "@RscineWorkerBundle/Resources/config/routing.yml"
    prefix:   /

rscine_core:
    resource: "@RscineCoreBundle/Resources/config/routing.yml"
    prefix:   /

rscine_offer:
    resource: "@RscineOfferBundle/Resources/config/routing.yml"
    prefix:   /

rscine_user:
    resource: "@RscineUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api:
    type: rest
    resource: "api.yml"
    prefix: api/v1

api_login_check:
    path: /api/login_check
