services:

    app.form.type.user_registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type , alias: appbundle_user_registration}

    app.form.type.user_profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type , alias: appbundle_user_profile}