AppBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: user.username.not_blank
        email:
            - NotBlank:
                message: user.email.not_blank
            - Email:
                message: user.email.not_valid
                checkMX: true
        plainPassword:
            - NotBlank:
                message: user.plain_password.not_blank
            - Length:
                min: 8
                max: 50
                minMessage: user.plain_password.too_short
                maxMessage: user.plain_password.too_long
