Rscine\AppBundle\Entity\Company:
    constraints: ~
    properties:
        name:
            - NotBlank:
                message: company.name.not_blank
                groups: [Default]
        siret:
            - NotBlank:
                message: company.siret.not_blank
                groups: [Default]